include $(CLEAR_VARS)
LOCAL_MODULE := com.ustwo.lwp.apk
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := com.ustwo.lwp.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
